name: eNorge
favicon: null
layout_spectrum: 0
typography_spectrum: 0.28187
title: Spill eRepublik
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0001'
    - '#ffffff'
    - '#010080'
    - '#828282'
    - '#e29c9b'
  brandStrength: 0.5251136221922934
  lightness: 0.24837688566185534
  saturation: 0.5622625073883682
  rhythmicContrast: 0.17056523682549596
purpose: []
