name: eNorge
favicon: null
layout_spectrum: 0.20357
typography_spectrum: 0.28187
title: Spill eRepublik
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0001'
    - '#ffffff'
    - '#010080'
    - '#828282'
    - '#e29c9b'
  brandStrength: 0.5625
  lightness: 0.125
  saturation: 0.5622625073883682
  rhythmicContrast: 0.5
purpose: []
